<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

use App\Models\User;
use App\Models\UserAccess;
use App\Models\ContractInformation;

class UserDefaultAccessSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "coordinador@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "administrativo@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "jefearea@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "guardian@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "supervisor@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "empleado@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "visitante@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "empleador@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],

            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "gerente@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],

            [
                'name' => "Jose Alberto",
                'surname' => "Rosa Mañan",
                'email' => "gestorriesgo@example.com",
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'remember_token' => Str::random(10),
                'document_type_id' => \App\Models\DocumentType::inRandomOrder()->first()->id,
                'document_number' => Str::random(10),
                'phone_number' => "8094202055",
                'dob' => "1997-04-29",
                'profession_id' => \App\Models\Profession::inRandomOrder()->first()->id,
                'brigade_id' => \App\Models\Brigade::inRandomOrder()->first()->id,
                'gender_id' => \App\Models\Gender::inRandomOrder()->first()->id,
                'em_co_name' => "Natalia Manan",
                'em_co_phone' => "8094347228",
                'blood_type_id' => \App\Models\BloodType::inRandomOrder()->first()->id,
                'city_id' => \App\Models\City::inRandomOrder()->first()->id,
            ],
        ];

        foreach ($users as $key => $user) {
            $createdUser = User::create($user);
            $access = ['user_id' => $createdUser->id, 'role_id' => $key+1, 'company_id' => 1, 'from' => '2023-01-01', 'until' => '2024-12-01'];
            ContractInformation::create(['user_id' => $createdUser->id, 
                                            'position_id' => \App\Models\Position::inRandomOrder()->first()->id,
                                            'company_id' => 1,
                                        ]);
            UserAccess::create($access);
        }
    }
}
